// js/cards.js
// Fictional athletes and teams. No real player likenesses are used.
// realisticArt paths are optional. If the JPG/PNG file is missing, the game falls back to the SVG cardArt.

const SPORTS = {
  "Football": {
    "emoji": "🏈",
    "color": "#7c3f1d"
  },
  "Basketball": {
    "emoji": "🏀",
    "color": "#d97706"
  },
  "Soccer": {
    "emoji": "⚽",
    "color": "#15803d"
  },
  "Baseball": {
    "emoji": "⚾",
    "color": "#2563eb"
  }
};

const CARDS = [
  {
    "id": "fb_qb_ross",
    "sport": "Football",
    "name": "Mason Ross",
    "team": "Dallas Outlaws",
    "pos": "QB",
    "emoji": "\ud83c\udfc8",
    "rarity": "Common",
    "off": 62,
    "def": 35,
    "ath": 58,
    "iq": 68,
    "desc": "Accurate pocket passer with calm late-game reads.",
    "art": "assets/players/fb_qb_ross.svg",
    "cardArt": "assets/cards/fb_qb_ross.svg",
    "realisticArt": "assets/realistic/fb_qb_ross.jpg"
  },
  {
    "id": "fb_rb_knox",
    "sport": "Football",
    "name": "Trey Knox",
    "team": "Philly Liberty",
    "pos": "RB",
    "emoji": "\ud83c\udfc8",
    "rarity": "Common",
    "off": 64,
    "def": 38,
    "ath": 72,
    "iq": 55,
    "desc": "One-cut runner who breaks arm tackles.",
    "art": "assets/players/fb_rb_knox.svg",
    "cardArt": "assets/cards/fb_rb_knox.svg",
    "realisticArt": "assets/realistic/fb_rb_knox.jpg"
  },
  {
    "id": "fb_wr_blaze",
    "sport": "Football",
    "name": "Devin Blaze",
    "team": "Miami Waves",
    "pos": "WR",
    "emoji": "\ud83c\udfc8",
    "rarity": "Uncommon",
    "off": 70,
    "def": 33,
    "ath": 78,
    "iq": 58,
    "desc": "Deep-ball threat with track speed.",
    "art": "assets/players/fb_wr_blaze.svg",
    "cardArt": "assets/cards/fb_wr_blaze.svg",
    "realisticArt": "assets/realistic/fb_wr_blaze.jpg"
  },
  {
    "id": "fb_lb_crowe",
    "sport": "Football",
    "name": "Cal Crowe",
    "team": "Chicago Steel",
    "pos": "LB",
    "emoji": "\ud83c\udfc8",
    "rarity": "Uncommon",
    "off": 35,
    "def": 75,
    "ath": 67,
    "iq": 66,
    "desc": "Sideline-to-sideline linebacker.",
    "art": "assets/players/fb_lb_crowe.svg",
    "cardArt": "assets/cards/fb_lb_crowe.svg",
    "realisticArt": "assets/realistic/fb_lb_crowe.jpg"
  },
  {
    "id": "fb_s_hayes",
    "sport": "Football",
    "name": "Jalen Hayes",
    "team": "Denver Peaks",
    "pos": "S",
    "emoji": "\ud83c\udfc8",
    "rarity": "Rare",
    "off": 42,
    "def": 82,
    "ath": 80,
    "iq": 74,
    "desc": "Ballhawk safety with elite closing speed.",
    "art": "assets/players/fb_s_hayes.svg",
    "cardArt": "assets/cards/fb_s_hayes.svg",
    "realisticArt": "assets/realistic/fb_s_hayes.jpg"
  },
  {
    "id": "fb_qb_stone",
    "sport": "Football",
    "name": "Austin Stone",
    "team": "New York Knights",
    "pos": "QB",
    "emoji": "\ud83c\udfc8",
    "rarity": "Rare",
    "off": 84,
    "def": 32,
    "ath": 63,
    "iq": 82,
    "desc": "Franchise arm with playoff poise.",
    "art": "assets/players/fb_qb_stone.svg",
    "cardArt": "assets/cards/fb_qb_stone.svg",
    "realisticArt": "assets/realistic/fb_qb_stone.jpg"
  },
  {
    "id": "fb_edge_vega",
    "sport": "Football",
    "name": "Rico Vega",
    "team": "LA Suns",
    "pos": "EDGE",
    "emoji": "\ud83c\udfc8",
    "rarity": "Epic",
    "off": 30,
    "def": 91,
    "ath": 86,
    "iq": 74,
    "desc": "Game-wrecking pass rusher.",
    "art": "assets/players/fb_edge_vega.svg",
    "cardArt": "assets/cards/fb_edge_vega.svg",
    "realisticArt": "assets/realistic/fb_edge_vega.jpg"
  },
  {
    "id": "fb_star_king",
    "sport": "Football",
    "name": "King Jefferson",
    "team": "Atlanta Firebirds",
    "pos": "WR",
    "emoji": "\ud83c\udfc8",
    "rarity": "Legendary",
    "off": 96,
    "def": 40,
    "ath": 97,
    "iq": 86,
    "desc": "Highlight-machine receiver and collector favorite.",
    "art": "assets/players/fb_star_king.svg",
    "cardArt": "assets/cards/fb_star_king.svg",
    "realisticArt": "assets/realistic/fb_star_king.jpg"
  },
  {
    "id": "bb_pg_carter",
    "sport": "Basketball",
    "name": "Eli Carter",
    "team": "Chicago Breeze",
    "pos": "PG",
    "emoji": "\ud83c\udfc0",
    "rarity": "Common",
    "off": 61,
    "def": 49,
    "ath": 65,
    "iq": 69,
    "desc": "Steady floor general with clean passing.",
    "art": "assets/players/bb_pg_carter.svg",
    "cardArt": "assets/cards/bb_pg_carter.svg",
    "realisticArt": "assets/realistic/bb_pg_carter.jpg"
  },
  {
    "id": "bb_sg_miles",
    "sport": "Basketball",
    "name": "Andre Miles",
    "team": "Brooklyn Towers",
    "pos": "SG",
    "emoji": "\ud83c\udfc0",
    "rarity": "Common",
    "off": 66,
    "def": 44,
    "ath": 64,
    "iq": 55,
    "desc": "Catch-and-shoot guard who heats up fast.",
    "art": "assets/players/bb_sg_miles.svg",
    "cardArt": "assets/cards/bb_sg_miles.svg",
    "realisticArt": "assets/realistic/bb_sg_miles.jpg"
  },
  {
    "id": "bb_sf_banks",
    "sport": "Basketball",
    "name": "Noah Banks",
    "team": "LA Palms",
    "pos": "SF",
    "emoji": "\ud83c\udfc0",
    "rarity": "Uncommon",
    "off": 70,
    "def": 62,
    "ath": 72,
    "iq": 61,
    "desc": "Two-way wing with smooth finishing.",
    "art": "assets/players/bb_sf_banks.svg",
    "cardArt": "assets/cards/bb_sf_banks.svg",
    "realisticArt": "assets/realistic/bb_sf_banks.jpg"
  },
  {
    "id": "bb_pf_rios",
    "sport": "Basketball",
    "name": "Mateo Rios",
    "team": "San Antonio Stars",
    "pos": "PF",
    "emoji": "\ud83c\udfc0",
    "rarity": "Uncommon",
    "off": 63,
    "def": 72,
    "ath": 70,
    "iq": 63,
    "desc": "Physical forward who owns the glass.",
    "art": "assets/players/bb_pf_rios.svg",
    "cardArt": "assets/cards/bb_pf_rios.svg",
    "realisticArt": "assets/realistic/bb_pf_rios.jpg"
  },
  {
    "id": "bb_c_okoro",
    "sport": "Basketball",
    "name": "Bemi Okoro",
    "team": "Houston Orbit",
    "pos": "C",
    "emoji": "\ud83c\udfc0",
    "rarity": "Rare",
    "off": 73,
    "def": 84,
    "ath": 74,
    "iq": 67,
    "desc": "Rim protector with soft hands.",
    "art": "assets/players/bb_c_okoro.svg",
    "cardArt": "assets/cards/bb_c_okoro.svg",
    "realisticArt": "assets/realistic/bb_c_okoro.jpg"
  },
  {
    "id": "bb_pg_lynch",
    "sport": "Basketball",
    "name": "Tyson Lynch",
    "team": "New York Empire",
    "pos": "PG",
    "emoji": "\ud83c\udfc0",
    "rarity": "Rare",
    "off": 86,
    "def": 58,
    "ath": 82,
    "iq": 83,
    "desc": "Late-clock shot creator.",
    "art": "assets/players/bb_pg_lynch.svg",
    "cardArt": "assets/cards/bb_pg_lynch.svg",
    "realisticArt": "assets/realistic/bb_pg_lynch.jpg"
  },
  {
    "id": "bb_sg_nova",
    "sport": "Basketball",
    "name": "Kai Nova",
    "team": "Phoenix Heat",
    "pos": "SG",
    "emoji": "\ud83c\udfc0",
    "rarity": "Epic",
    "off": 93,
    "def": 62,
    "ath": 86,
    "iq": 79,
    "desc": "Three-level scorer with logo range.",
    "art": "assets/players/bb_sg_nova.svg",
    "cardArt": "assets/cards/bb_sg_nova.svg",
    "realisticArt": "assets/realistic/bb_sg_nova.jpg"
  },
  {
    "id": "bb_star_prime",
    "sport": "Basketball",
    "name": "Malik Prime",
    "team": "Atlanta Nighthawks",
    "pos": "SG",
    "emoji": "\ud83c\udfc0",
    "rarity": "Legendary",
    "off": 97,
    "def": 88,
    "ath": 95,
    "iq": 92,
    "desc": "All-world wing who changes every matchup.",
    "art": "assets/players/bb_star_prime.svg",
    "cardArt": "assets/cards/bb_star_prime.svg",
    "realisticArt": "assets/realistic/bb_star_prime.jpg"
  },
  {
    "id": "sc_st_holt",
    "sport": "Soccer",
    "name": "Leo Holt",
    "team": "London City",
    "pos": "ST",
    "emoji": "\u26bd",
    "rarity": "Common",
    "off": 64,
    "def": 31,
    "ath": 66,
    "iq": 58,
    "desc": "Classic striker who lives near the box.",
    "art": "assets/players/sc_st_holt.svg",
    "cardArt": "assets/cards/sc_st_holt.svg",
    "realisticArt": "assets/realistic/sc_st_holt.jpg"
  },
  {
    "id": "sc_cm_santos",
    "sport": "Soccer",
    "name": "Nico Santos",
    "team": "Madrid Royals",
    "pos": "CM",
    "emoji": "\u26bd",
    "rarity": "Common",
    "off": 58,
    "def": 55,
    "ath": 61,
    "iq": 70,
    "desc": "Keeps possession moving with simple passes.",
    "art": "assets/players/sc_cm_santos.svg",
    "cardArt": "assets/cards/sc_cm_santos.svg",
    "realisticArt": "assets/realistic/sc_cm_santos.jpg"
  },
  {
    "id": "sc_w_ramirez",
    "sport": "Soccer",
    "name": "Dante Ramirez",
    "team": "Miami Union",
    "pos": "W",
    "emoji": "\u26bd",
    "rarity": "Uncommon",
    "off": 73,
    "def": 42,
    "ath": 82,
    "iq": 60,
    "desc": "Explosive winger with quick feet.",
    "art": "assets/players/sc_w_ramirez.svg",
    "cardArt": "assets/cards/sc_w_ramirez.svg",
    "realisticArt": "assets/realistic/sc_w_ramirez.jpg"
  },
  {
    "id": "sc_cb_ward",
    "sport": "Soccer",
    "name": "Oliver Ward",
    "team": "Manchester Forge",
    "pos": "CB",
    "emoji": "\u26bd",
    "rarity": "Uncommon",
    "off": 38,
    "def": 78,
    "ath": 64,
    "iq": 72,
    "desc": "No-nonsense center back.",
    "art": "assets/players/sc_cb_ward.svg",
    "cardArt": "assets/cards/sc_cb_ward.svg",
    "realisticArt": "assets/realistic/sc_cb_ward.jpg"
  },
  {
    "id": "sc_gk_ito",
    "sport": "Soccer",
    "name": "Kenji Ito",
    "team": "Tokyo Harbor",
    "pos": "GK",
    "emoji": "\u26bd",
    "rarity": "Rare",
    "off": 25,
    "def": 88,
    "ath": 76,
    "iq": 79,
    "desc": "Reflex keeper with excellent positioning.",
    "art": "assets/players/sc_gk_ito.svg",
    "cardArt": "assets/cards/sc_gk_ito.svg",
    "realisticArt": "assets/realistic/sc_gk_ito.jpg"
  },
  {
    "id": "sc_am_silva",
    "sport": "Soccer",
    "name": "Marco Silva",
    "team": "Lisbon Lions",
    "pos": "CAM",
    "emoji": "\u26bd",
    "rarity": "Rare",
    "off": 86,
    "def": 47,
    "ath": 74,
    "iq": 87,
    "desc": "Chance creator with elite vision.",
    "art": "assets/players/sc_am_silva.svg",
    "cardArt": "assets/cards/sc_am_silva.svg",
    "realisticArt": "assets/realistic/sc_am_silva.jpg"
  },
  {
    "id": "sc_st_moreau",
    "sport": "Soccer",
    "name": "Theo Moreau",
    "team": "Paris Metro",
    "pos": "ST",
    "emoji": "\u26bd",
    "rarity": "Epic",
    "off": 94,
    "def": 40,
    "ath": 91,
    "iq": 82,
    "desc": "Clinical finisher with cold-blooded composure.",
    "art": "assets/players/sc_st_moreau.svg",
    "cardArt": "assets/cards/sc_st_moreau.svg",
    "realisticArt": "assets/realistic/sc_st_moreau.jpg"
  },
  {
    "id": "sc_star_soleil",
    "sport": "Soccer",
    "name": "Julian Soleil",
    "team": "Los Angeles Strikers",
    "pos": "LW",
    "emoji": "\u26bd",
    "rarity": "Legendary",
    "off": 98,
    "def": 52,
    "ath": 99,
    "iq": 91,
    "desc": "Generational winger with impossible control.",
    "art": "assets/players/sc_star_soleil.svg",
    "cardArt": "assets/cards/sc_star_soleil.svg",
    "realisticArt": "assets/realistic/sc_star_soleil.jpg"
  },
  {
    "id": "bs_sp_miller",
    "sport": "Baseball",
    "name": "Grant Miller",
    "team": "St. Louis Arches",
    "pos": "SP",
    "emoji": "\u26be",
    "rarity": "Common",
    "off": 28,
    "def": 67,
    "ath": 54,
    "iq": 66,
    "desc": "Reliable starter with a heavy sinker.",
    "art": "assets/players/bs_sp_miller.svg",
    "cardArt": "assets/cards/bs_sp_miller.svg",
    "realisticArt": "assets/realistic/bs_sp_miller.jpg"
  },
  {
    "id": "bs_2b_wells",
    "sport": "Baseball",
    "name": "Cam Wells",
    "team": "Boston Harbor",
    "pos": "2B",
    "emoji": "\u26be",
    "rarity": "Common",
    "off": 58,
    "def": 61,
    "ath": 62,
    "iq": 60,
    "desc": "Contact hitter with tidy defense.",
    "art": "assets/players/bs_2b_wells.svg",
    "cardArt": "assets/cards/bs_2b_wells.svg",
    "realisticArt": "assets/realistic/bs_2b_wells.jpg"
  },
  {
    "id": "bs_cf_reed",
    "sport": "Baseball",
    "name": "Jordan Reed",
    "team": "Seattle Pines",
    "pos": "CF",
    "emoji": "\u26be",
    "rarity": "Uncommon",
    "off": 66,
    "def": 74,
    "ath": 78,
    "iq": 62,
    "desc": "Gap-to-gap speedster.",
    "art": "assets/players/bs_cf_reed.svg",
    "cardArt": "assets/cards/bs_cf_reed.svg",
    "realisticArt": "assets/realistic/bs_cf_reed.jpg"
  },
  {
    "id": "bs_c_morales",
    "sport": "Baseball",
    "name": "Luis Morales",
    "team": "Arizona Dust",
    "pos": "C",
    "emoji": "\u26be",
    "rarity": "Uncommon",
    "off": 55,
    "def": 76,
    "ath": 52,
    "iq": 78,
    "desc": "Smart catcher who controls the staff.",
    "art": "assets/players/bs_c_morales.svg",
    "cardArt": "assets/cards/bs_c_morales.svg",
    "realisticArt": "assets/realistic/bs_c_morales.jpg"
  },
  {
    "id": "bs_1b_bishop",
    "sport": "Baseball",
    "name": "Duke Bishop",
    "team": "New York Pinstripes",
    "pos": "1B",
    "emoji": "\u26be",
    "rarity": "Rare",
    "off": 86,
    "def": 58,
    "ath": 55,
    "iq": 70,
    "desc": "Power bat built for the short porch.",
    "art": "assets/players/bs_1b_bishop.svg",
    "cardArt": "assets/cards/bs_1b_bishop.svg",
    "realisticArt": "assets/realistic/bs_1b_bishop.jpg"
  },
  {
    "id": "bs_cp_frost",
    "sport": "Baseball",
    "name": "Cole Frost",
    "team": "Minnesota North",
    "pos": "CP",
    "emoji": "\u26be",
    "rarity": "Rare",
    "off": 22,
    "def": 91,
    "ath": 72,
    "iq": 76,
    "desc": "Closer with ice-water command.",
    "art": "assets/players/bs_cp_frost.svg",
    "cardArt": "assets/cards/bs_cp_frost.svg",
    "realisticArt": "assets/realistic/bs_cp_frost.jpg"
  },
  {
    "id": "bs_ss_torres",
    "sport": "Baseball",
    "name": "Rafa Torres",
    "team": "San Diego Surf",
    "pos": "SS",
    "emoji": "\u26be",
    "rarity": "Epic",
    "off": 87,
    "def": 88,
    "ath": 86,
    "iq": 82,
    "desc": "Five-tool shortstop and fan favorite.",
    "art": "assets/players/bs_ss_torres.svg",
    "cardArt": "assets/cards/bs_ss_torres.svg",
    "realisticArt": "assets/realistic/bs_ss_torres.jpg"
  },
  {
    "id": "bs_star_hammer",
    "sport": "Baseball",
    "name": "Hank Hammer",
    "team": "Boston Rise",
    "pos": "1B",
    "emoji": "\u26be",
    "rarity": "Legendary",
    "off": 99,
    "def": 78,
    "ath": 82,
    "iq": 88,
    "desc": "Moonshot slugger with legendary exit velocity.",
    "art": "assets/players/bs_star_hammer.svg",
    "cardArt": "assets/cards/bs_star_hammer.svg",
    "realisticArt": "assets/realistic/bs_star_hammer.jpg"
  },
  {
    "id": "fb_qb_frost_01",
    "sport": "Football",
    "name": "Cam Frost",
    "team": "Seattle Orcas",
    "pos": "QB",
    "emoji": "\ud83c\udfc8",
    "rarity": "Common",
    "off": 77,
    "def": 51,
    "ath": 63,
    "iq": 83,
    "desc": "Depth QB who helps complete the binder.",
    "art": "assets/players/fb_qb_frost_01.svg",
    "cardArt": "assets/cards/fb_qb_frost_01.svg",
    "realisticArt": "assets/cards/fb_qb_frost_01.svg"
  },
  {
    "id": "fb_rb_morrow_02",
    "sport": "Football",
    "name": "Luca Morrow",
    "team": "Boston Harbor",
    "pos": "RB",
    "emoji": "\ud83c\udfc8",
    "rarity": "Common",
    "off": 63,
    "def": 42,
    "ath": 66,
    "iq": 56,
    "desc": "Depth RB who helps complete the binder.",
    "art": "assets/players/fb_rb_morrow_02.svg",
    "cardArt": "assets/cards/fb_rb_morrow_02.svg",
    "realisticArt": "assets/cards/fb_rb_morrow_02.svg"
  },
  {
    "id": "fb_wr_fox_03",
    "sport": "Football",
    "name": "Cam Fox",
    "team": "Phoenix Heat",
    "pos": "WR",
    "emoji": "\ud83c\udfc8",
    "rarity": "Common",
    "off": 69,
    "def": 47,
    "ath": 64,
    "iq": 56,
    "desc": "Depth WR who helps complete the binder.",
    "art": "assets/players/fb_wr_fox_03.svg",
    "cardArt": "assets/cards/fb_wr_fox_03.svg",
    "realisticArt": "assets/cards/fb_wr_fox_03.svg"
  },
  {
    "id": "fb_te_price_04",
    "sport": "Football",
    "name": "Orion Price",
    "team": "Nashville Thunder",
    "pos": "TE",
    "emoji": "\ud83c\udfc8",
    "rarity": "Common",
    "off": 60,
    "def": 36,
    "ath": 60,
    "iq": 51,
    "desc": "Depth TE who helps complete the binder.",
    "art": "assets/players/fb_te_price_04.svg",
    "cardArt": "assets/cards/fb_te_price_04.svg",
    "realisticArt": "assets/cards/fb_te_price_04.svg"
  },
  {
    "id": "fb_lb_pierce_05",
    "sport": "Football",
    "name": "Cruz Pierce",
    "team": "Vegas Voltage",
    "pos": "LB",
    "emoji": "\ud83c\udfc8",
    "rarity": "Common",
    "off": 51,
    "def": 78,
    "ath": 66,
    "iq": 74,
    "desc": "Depth LB who helps complete the binder.",
    "art": "assets/players/fb_lb_pierce_05.svg",
    "cardArt": "assets/cards/fb_lb_pierce_05.svg",
    "realisticArt": "assets/cards/fb_lb_pierce_05.svg"
  },
  {
    "id": "fb_cb_holloway_06",
    "sport": "Football",
    "name": "Kade Holloway",
    "team": "Carolina Kings",
    "pos": "CB",
    "emoji": "\ud83c\udfc8",
    "rarity": "Common",
    "off": 47,
    "def": 74,
    "ath": 66,
    "iq": 60,
    "desc": "Depth CB who helps complete the binder.",
    "art": "assets/players/fb_cb_holloway_06.svg",
    "cardArt": "assets/cards/fb_cb_holloway_06.svg",
    "realisticArt": "assets/cards/fb_cb_holloway_06.svg"
  },
  {
    "id": "fb_s_bennett_07",
    "sport": "Football",
    "name": "Reid Bennett",
    "team": "Portland Pines",
    "pos": "S",
    "emoji": "\ud83c\udfc8",
    "rarity": "Common",
    "off": 47,
    "def": 77,
    "ath": 76,
    "iq": 70,
    "desc": "Depth S who helps complete the binder.",
    "art": "assets/players/fb_s_bennett_07.svg",
    "cardArt": "assets/cards/fb_s_bennett_07.svg",
    "realisticArt": "assets/cards/fb_s_bennett_07.svg"
  },
  {
    "id": "fb_edge_rhodes_08",
    "sport": "Football",
    "name": "Dante Rhodes",
    "team": "San Diego Surf",
    "pos": "EDGE",
    "emoji": "\ud83c\udfc8",
    "rarity": "Common",
    "off": 56,
    "def": 72,
    "ath": 67,
    "iq": 64,
    "desc": "Depth EDGE who helps complete the binder.",
    "art": "assets/players/fb_edge_rhodes_08.svg",
    "cardArt": "assets/cards/fb_edge_rhodes_08.svg",
    "realisticArt": "assets/cards/fb_edge_rhodes_08.svg"
  },
  {
    "id": "fb_dt_page_09",
    "sport": "Football",
    "name": "Cruz Page",
    "team": "Seattle Orcas",
    "pos": "DT",
    "emoji": "\ud83c\udfc8",
    "rarity": "Common",
    "off": 31,
    "def": 63,
    "ath": 48,
    "iq": 56,
    "desc": "Depth DT who helps complete the binder.",
    "art": "assets/players/fb_dt_page_09.svg",
    "cardArt": "assets/cards/fb_dt_page_09.svg",
    "realisticArt": "assets/cards/fb_dt_page_09.svg"
  },
  {
    "id": "fb_k_mason_10",
    "sport": "Football",
    "name": "Zion Mason",
    "team": "Boston Harbor",
    "pos": "K",
    "emoji": "\ud83c\udfc8",
    "rarity": "Common",
    "off": 73,
    "def": 44,
    "ath": 61,
    "iq": 70,
    "desc": "Depth K who helps complete the binder.",
    "art": "assets/players/fb_k_mason_10.svg",
    "cardArt": "assets/cards/fb_k_mason_10.svg",
    "realisticArt": "assets/cards/fb_k_mason_10.svg"
  },
  {
    "id": "fb_qb_valdez_11",
    "sport": "Football",
    "name": "Talon Valdez",
    "team": "Phoenix Heat",
    "pos": "QB",
    "emoji": "\ud83c\udfc8",
    "rarity": "Uncommon",
    "off": 83,
    "def": 57,
    "ath": 67,
    "iq": 76,
    "desc": "Useful rotation QB with upgrade potential.",
    "art": "assets/players/fb_qb_valdez_11.svg",
    "cardArt": "assets/cards/fb_qb_valdez_11.svg",
    "realisticArt": "assets/cards/fb_qb_valdez_11.svg"
  },
  {
    "id": "fb_rb_reyes_12",
    "sport": "Football",
    "name": "Nico Reyes",
    "team": "Nashville Thunder",
    "pos": "RB",
    "emoji": "\ud83c\udfc8",
    "rarity": "Uncommon",
    "off": 77,
    "def": 54,
    "ath": 76,
    "iq": 76,
    "desc": "Useful rotation RB with upgrade potential.",
    "art": "assets/players/fb_rb_reyes_12.svg",
    "cardArt": "assets/cards/fb_rb_reyes_12.svg",
    "realisticArt": "assets/cards/fb_rb_reyes_12.svg"
  },
  {
    "id": "fb_wr_mills_13",
    "sport": "Football",
    "name": "Elias Mills",
    "team": "Vegas Voltage",
    "pos": "WR",
    "emoji": "\ud83c\udfc8",
    "rarity": "Uncommon",
    "off": 81,
    "def": 64,
    "ath": 77,
    "iq": 70,
    "desc": "Useful rotation WR with upgrade potential.",
    "art": "assets/players/fb_wr_mills_13.svg",
    "cardArt": "assets/cards/fb_wr_mills_13.svg",
    "realisticArt": "assets/cards/fb_wr_mills_13.svg"
  },
  {
    "id": "fb_te_mercer_14",
    "sport": "Football",
    "name": "Ari Mercer",
    "team": "Carolina Kings",
    "pos": "TE",
    "emoji": "\ud83c\udfc8",
    "rarity": "Uncommon",
    "off": 85,
    "def": 60,
    "ath": 60,
    "iq": 71,
    "desc": "Useful rotation TE with upgrade potential.",
    "art": "assets/players/fb_te_mercer_14.svg",
    "cardArt": "assets/cards/fb_te_mercer_14.svg",
    "realisticArt": "assets/cards/fb_te_mercer_14.svg"
  },
  {
    "id": "fb_lb_hunt_15",
    "sport": "Football",
    "name": "Theo Hunt",
    "team": "Portland Pines",
    "pos": "LB",
    "emoji": "\ud83c\udfc8",
    "rarity": "Uncommon",
    "off": 51,
    "def": 72,
    "ath": 61,
    "iq": 59,
    "desc": "Useful rotation LB with upgrade potential.",
    "art": "assets/players/fb_lb_hunt_15.svg",
    "cardArt": "assets/cards/fb_lb_hunt_15.svg",
    "realisticArt": "assets/cards/fb_lb_hunt_15.svg"
  },
  {
    "id": "fb_cb_morrow_16",
    "sport": "Football",
    "name": "Reid Morrow",
    "team": "San Diego Surf",
    "pos": "CB",
    "emoji": "\ud83c\udfc8",
    "rarity": "Uncommon",
    "off": 57,
    "def": 72,
    "ath": 67,
    "iq": 55,
    "desc": "Useful rotation CB with upgrade potential.",
    "art": "assets/players/fb_cb_morrow_16.svg",
    "cardArt": "assets/cards/fb_cb_morrow_16.svg",
    "realisticArt": "assets/cards/fb_cb_morrow_16.svg"
  },
  {
    "id": "fb_s_price_17",
    "sport": "Football",
    "name": "Nico Price",
    "team": "Seattle Orcas",
    "pos": "S",
    "emoji": "\ud83c\udfc8",
    "rarity": "Rare",
    "off": 56,
    "def": 86,
    "ath": 90,
    "iq": 69,
    "desc": "Reliable high-ceiling S for competitive lineups.",
    "art": "assets/players/fb_s_price_17.svg",
    "cardArt": "assets/cards/fb_s_price_17.svg",
    "realisticArt": "assets/cards/fb_s_price_17.svg"
  },
  {
    "id": "fb_edge_sterling_18",
    "sport": "Football",
    "name": "Jonah Sterling",
    "team": "Boston Harbor",
    "pos": "EDGE",
    "emoji": "\ud83c\udfc8",
    "rarity": "Rare",
    "off": 70,
    "def": 94,
    "ath": 90,
    "iq": 85,
    "desc": "Reliable high-ceiling EDGE for competitive lineups.",
    "art": "assets/players/fb_edge_sterling_18.svg",
    "cardArt": "assets/cards/fb_edge_sterling_18.svg",
    "realisticArt": "assets/cards/fb_edge_sterling_18.svg"
  },
  {
    "id": "fb_dt_cross_19",
    "sport": "Football",
    "name": "Jonah Cross",
    "team": "Phoenix Heat",
    "pos": "DT",
    "emoji": "\ud83c\udfc8",
    "rarity": "Rare",
    "off": 75,
    "def": 99,
    "ath": 92,
    "iq": 86,
    "desc": "Reliable high-ceiling DT for competitive lineups.",
    "art": "assets/players/fb_dt_cross_19.svg",
    "cardArt": "assets/cards/fb_dt_cross_19.svg",
    "realisticArt": "assets/cards/fb_dt_cross_19.svg"
  },
  {
    "id": "fb_k_west_20",
    "sport": "Football",
    "name": "Julius West",
    "team": "Nashville Thunder",
    "pos": "K",
    "emoji": "\ud83c\udfc8",
    "rarity": "Rare",
    "off": 93,
    "def": 57,
    "ath": 69,
    "iq": 74,
    "desc": "Reliable high-ceiling K for competitive lineups.",
    "art": "assets/players/fb_k_west_20.svg",
    "cardArt": "assets/cards/fb_k_west_20.svg",
    "realisticArt": "assets/cards/fb_k_west_20.svg"
  },
  {
    "id": "fb_qb_ford_21",
    "sport": "Football",
    "name": "Makai Ford",
    "team": "Vegas Voltage",
    "pos": "QB",
    "emoji": "\ud83c\udfc8",
    "rarity": "Epic",
    "off": 99,
    "def": 67,
    "ath": 75,
    "iq": 98,
    "desc": "Premium QB with elite impact traits.",
    "art": "assets/players/fb_qb_ford_21.svg",
    "cardArt": "assets/cards/fb_qb_ford_21.svg",
    "realisticArt": "assets/cards/fb_qb_ford_21.svg"
  },
  {
    "id": "fb_rb_morrow_22",
    "sport": "Football",
    "name": "Marco Morrow",
    "team": "Carolina Kings",
    "pos": "RB",
    "emoji": "\ud83c\udfc8",
    "rarity": "Legendary",
    "off": 99,
    "def": 83,
    "ath": 99,
    "iq": 90,
    "desc": "Franchise-defining RB with chase-card upside.",
    "art": "assets/players/fb_rb_morrow_22.svg",
    "cardArt": "assets/cards/fb_rb_morrow_22.svg",
    "realisticArt": "assets/cards/fb_rb_morrow_22.svg"
  },
  {
    "id": "bb_pg_cross_01",
    "sport": "Basketball",
    "name": "Ronan Cross",
    "team": "Seattle Rain",
    "pos": "PG",
    "emoji": "\ud83c\udfc0",
    "rarity": "Common",
    "off": 84,
    "def": 63,
    "ath": 76,
    "iq": 79,
    "desc": "Depth PG who helps complete the binder.",
    "art": "assets/players/bb_pg_cross_01.svg",
    "cardArt": "assets/cards/bb_pg_cross_01.svg",
    "realisticArt": "assets/cards/bb_pg_cross_01.svg"
  },
  {
    "id": "bb_sg_bishop_02",
    "sport": "Basketball",
    "name": "Talon Bishop",
    "team": "Miami Vice",
    "pos": "SG",
    "emoji": "\ud83c\udfc0",
    "rarity": "Common",
    "off": 75,
    "def": 56,
    "ath": 63,
    "iq": 63,
    "desc": "Depth SG who helps complete the binder.",
    "art": "assets/players/bb_sg_bishop_02.svg",
    "cardArt": "assets/cards/bb_sg_bishop_02.svg",
    "realisticArt": "assets/cards/bb_sg_bishop_02.svg"
  },
  {
    "id": "bb_sf_rhodes_03",
    "sport": "Basketball",
    "name": "Makai Rhodes",
    "team": "Phoenix Comets",
    "pos": "SF",
    "emoji": "\ud83c\udfc0",
    "rarity": "Common",
    "off": 60,
    "def": 49,
    "ath": 57,
    "iq": 58,
    "desc": "Depth SF who helps complete the binder.",
    "art": "assets/players/bb_sf_rhodes_03.svg",
    "cardArt": "assets/cards/bb_sf_rhodes_03.svg",
    "realisticArt": "assets/cards/bb_sf_rhodes_03.svg"
  },
  {
    "id": "bb_pf_cannon_04",
    "sport": "Basketball",
    "name": "Nico Cannon",
    "team": "Detroit Motors",
    "pos": "PF",
    "emoji": "\ud83c\udfc0",
    "rarity": "Common",
    "off": 58,
    "def": 65,
    "ath": 54,
    "iq": 52,
    "desc": "Depth PF who helps complete the binder.",
    "art": "assets/players/bb_pf_cannon_04.svg",
    "cardArt": "assets/cards/bb_pf_cannon_04.svg",
    "realisticArt": "assets/cards/bb_pf_cannon_04.svg"
  },
  {
    "id": "bb_c_valdez_05",
    "sport": "Basketball",
    "name": "Felix Valdez",
    "team": "Orlando Magic City",
    "pos": "C",
    "emoji": "\ud83c\udfc0",
    "rarity": "Common",
    "off": 59,
    "def": 71,
    "ath": 70,
    "iq": 67,
    "desc": "Depth C who helps complete the binder.",
    "art": "assets/players/bb_c_valdez_05.svg",
    "cardArt": "assets/cards/bb_c_valdez_05.svg",
    "realisticArt": "assets/cards/bb_c_valdez_05.svg"
  },
  {
    "id": "bb_pg_ford_06",
    "sport": "Basketball",
    "name": "Reid Ford",
    "team": "Portland Roses",
    "pos": "PG",
    "emoji": "\ud83c\udfc0",
    "rarity": "Common",
    "off": 62,
    "def": 64,
    "ath": 58,
    "iq": 62,
    "desc": "Depth PG who helps complete the binder.",
    "art": "assets/players/bb_pg_ford_06.svg",
    "cardArt": "assets/cards/bb_pg_ford_06.svg",
    "realisticArt": "assets/cards/bb_pg_ford_06.svg"
  },
  {
    "id": "bb_sg_reyes_07",
    "sport": "Basketball",
    "name": "Theo Reyes",
    "team": "Vegas Aces",
    "pos": "SG",
    "emoji": "\ud83c\udfc0",
    "rarity": "Common",
    "off": 52,
    "def": 45,
    "ath": 61,
    "iq": 58,
    "desc": "Depth SG who helps complete the binder.",
    "art": "assets/players/bb_sg_reyes_07.svg",
    "cardArt": "assets/cards/bb_sg_reyes_07.svg",
    "realisticArt": "assets/cards/bb_sg_reyes_07.svg"
  },
  {
    "id": "bb_sf_mercer_08",
    "sport": "Basketball",
    "name": "Cam Mercer",
    "team": "Kansas City Kings",
    "pos": "SF",
    "emoji": "\ud83c\udfc0",
    "rarity": "Common",
    "off": 63,
    "def": 58,
    "ath": 72,
    "iq": 62,
    "desc": "Depth SF who helps complete the binder.",
    "art": "assets/players/bb_sf_mercer_08.svg",
    "cardArt": "assets/cards/bb_sf_mercer_08.svg",
    "realisticArt": "assets/cards/bb_sf_mercer_08.svg"
  },
  {
    "id": "bb_pf_mills_09",
    "sport": "Basketball",
    "name": "Jonah Mills",
    "team": "Seattle Rain",
    "pos": "PF",
    "emoji": "\ud83c\udfc0",
    "rarity": "Common",
    "off": 65,
    "def": 68,
    "ath": 66,
    "iq": 58,
    "desc": "Depth PF who helps complete the binder.",
    "art": "assets/players/bb_pf_mills_09.svg",
    "cardArt": "assets/cards/bb_pf_mills_09.svg",
    "realisticArt": "assets/cards/bb_pf_mills_09.svg"
  },
  {
    "id": "bb_c_bridges_10",
    "sport": "Basketball",
    "name": "Zion Bridges",
    "team": "Miami Vice",
    "pos": "C",
    "emoji": "\ud83c\udfc0",
    "rarity": "Common",
    "off": 49,
    "def": 65,
    "ath": 63,
    "iq": 57,
    "desc": "Depth C who helps complete the binder.",
    "art": "assets/players/bb_c_bridges_10.svg",
    "cardArt": "assets/cards/bb_c_bridges_10.svg",
    "realisticArt": "assets/cards/bb_c_bridges_10.svg"
  },
  {
    "id": "bb_pg_hayes_11",
    "sport": "Basketball",
    "name": "Marco Hayes",
    "team": "Phoenix Comets",
    "pos": "PG",
    "emoji": "\ud83c\udfc0",
    "rarity": "Uncommon",
    "off": 73,
    "def": 60,
    "ath": 75,
    "iq": 76,
    "desc": "Useful rotation PG with upgrade potential.",
    "art": "assets/players/bb_pg_hayes_11.svg",
    "cardArt": "assets/cards/bb_pg_hayes_11.svg",
    "realisticArt": "assets/cards/bb_pg_hayes_11.svg"
  },
  {
    "id": "bb_sg_mercer_12",
    "sport": "Basketball",
    "name": "Ezra Mercer",
    "team": "Detroit Motors",
    "pos": "SG",
    "emoji": "\ud83c\udfc0",
    "rarity": "Uncommon",
    "off": 79,
    "def": 74,
    "ath": 76,
    "iq": 67,
    "desc": "Useful rotation SG with upgrade potential.",
    "art": "assets/players/bb_sg_mercer_12.svg",
    "cardArt": "assets/cards/bb_sg_mercer_12.svg",
    "realisticArt": "assets/cards/bb_sg_mercer_12.svg"
  },
  {
    "id": "bb_sf_sutton_13",
    "sport": "Basketball",
    "name": "Makai Sutton",
    "team": "Orlando Magic City",
    "pos": "SF",
    "emoji": "\ud83c\udfc0",
    "rarity": "Uncommon",
    "off": 61,
    "def": 64,
    "ath": 60,
    "iq": 55,
    "desc": "Useful rotation SF with upgrade potential.",
    "art": "assets/players/bb_sf_sutton_13.svg",
    "cardArt": "assets/cards/bb_sf_sutton_13.svg",
    "realisticArt": "assets/cards/bb_sf_sutton_13.svg"
  },
  {
    "id": "bb_pf_barrett_14",
    "sport": "Basketball",
    "name": "Reid Barrett",
    "team": "Portland Roses",
    "pos": "PF",
    "emoji": "\ud83c\udfc0",
    "rarity": "Uncommon",
    "off": 65,
    "def": 84,
    "ath": 77,
    "iq": 72,
    "desc": "Useful rotation PF with upgrade potential.",
    "art": "assets/players/bb_pf_barrett_14.svg",
    "cardArt": "assets/cards/bb_pf_barrett_14.svg",
    "realisticArt": "assets/cards/bb_pf_barrett_14.svg"
  },
  {
    "id": "bb_c_hale_15",
    "sport": "Basketball",
    "name": "Cruz Hale",
    "team": "Vegas Aces",
    "pos": "C",
    "emoji": "\ud83c\udfc0",
    "rarity": "Uncommon",
    "off": 78,
    "def": 83,
    "ath": 77,
    "iq": 70,
    "desc": "Useful rotation C with upgrade potential.",
    "art": "assets/players/bb_c_hale_15.svg",
    "cardArt": "assets/cards/bb_c_hale_15.svg",
    "realisticArt": "assets/cards/bb_c_hale_15.svg"
  },
  {
    "id": "bb_pg_cross_16",
    "sport": "Basketball",
    "name": "Rafael Cross",
    "team": "Kansas City Kings",
    "pos": "PG",
    "emoji": "\ud83c\udfc0",
    "rarity": "Uncommon",
    "off": 90,
    "def": 74,
    "ath": 79,
    "iq": 81,
    "desc": "Useful rotation PG with upgrade potential.",
    "art": "assets/players/bb_pg_cross_16.svg",
    "cardArt": "assets/cards/bb_pg_cross_16.svg",
    "realisticArt": "assets/cards/bb_pg_cross_16.svg"
  },
  {
    "id": "bb_sg_santiago_17",
    "sport": "Basketball",
    "name": "Ronan Santiago",
    "team": "Seattle Rain",
    "pos": "SG",
    "emoji": "\ud83c\udfc0",
    "rarity": "Rare",
    "off": 84,
    "def": 64,
    "ath": 78,
    "iq": 72,
    "desc": "Reliable high-ceiling SG for competitive lineups.",
    "art": "assets/players/bb_sg_santiago_17.svg",
    "cardArt": "assets/cards/bb_sg_santiago_17.svg",
    "realisticArt": "assets/cards/bb_sg_santiago_17.svg"
  },
  {
    "id": "bb_sf_ellis_18",
    "sport": "Basketball",
    "name": "Leo Ellis",
    "team": "Miami Vice",
    "pos": "SF",
    "emoji": "\ud83c\udfc0",
    "rarity": "Rare",
    "off": 84,
    "def": 71,
    "ath": 77,
    "iq": 74,
    "desc": "Reliable high-ceiling SF for competitive lineups.",
    "art": "assets/players/bb_sf_ellis_18.svg",
    "cardArt": "assets/cards/bb_sf_ellis_18.svg",
    "realisticArt": "assets/cards/bb_sf_ellis_18.svg"
  },
  {
    "id": "bb_pf_santiago_19",
    "sport": "Basketball",
    "name": "Malik Santiago",
    "team": "Phoenix Comets",
    "pos": "PF",
    "emoji": "\ud83c\udfc0",
    "rarity": "Rare",
    "off": 81,
    "def": 81,
    "ath": 76,
    "iq": 66,
    "desc": "Reliable high-ceiling PF for competitive lineups.",
    "art": "assets/players/bb_pf_santiago_19.svg",
    "cardArt": "assets/cards/bb_pf_santiago_19.svg",
    "realisticArt": "assets/cards/bb_pf_santiago_19.svg"
  },
  {
    "id": "bb_c_reed_20",
    "sport": "Basketball",
    "name": "Asher Reed",
    "team": "Detroit Motors",
    "pos": "C",
    "emoji": "\ud83c\udfc0",
    "rarity": "Rare",
    "off": 73,
    "def": 83,
    "ath": 88,
    "iq": 85,
    "desc": "Reliable high-ceiling C for competitive lineups.",
    "art": "assets/players/bb_c_reed_20.svg",
    "cardArt": "assets/cards/bb_c_reed_20.svg",
    "realisticArt": "assets/cards/bb_c_reed_20.svg"
  },
  {
    "id": "bb_pg_hunt_21",
    "sport": "Basketball",
    "name": "Micah Hunt",
    "team": "Orlando Magic City",
    "pos": "PG",
    "emoji": "\ud83c\udfc0",
    "rarity": "Epic",
    "off": 91,
    "def": 88,
    "ath": 88,
    "iq": 99,
    "desc": "Premium PG with elite impact traits.",
    "art": "assets/players/bb_pg_hunt_21.svg",
    "cardArt": "assets/cards/bb_pg_hunt_21.svg",
    "realisticArt": "assets/cards/bb_pg_hunt_21.svg"
  },
  {
    "id": "bb_sg_page_22",
    "sport": "Basketball",
    "name": "Tariq Page",
    "team": "Portland Roses",
    "pos": "SG",
    "emoji": "\ud83c\udfc0",
    "rarity": "Legendary",
    "off": 99,
    "def": 99,
    "ath": 98,
    "iq": 97,
    "desc": "Franchise-defining SG with chase-card upside.",
    "art": "assets/players/bb_sg_page_22.svg",
    "cardArt": "assets/cards/bb_sg_page_22.svg",
    "realisticArt": "assets/cards/bb_sg_page_22.svg"
  },
  {
    "id": "sc_st_hayes_01",
    "sport": "Soccer",
    "name": "Dorian Hayes",
    "team": "Austin Verde",
    "pos": "ST",
    "emoji": "\u26bd",
    "rarity": "Common",
    "off": 56,
    "def": 50,
    "ath": 55,
    "iq": 47,
    "desc": "Depth ST who helps complete the binder.",
    "art": "assets/players/sc_st_hayes_01.svg",
    "cardArt": "assets/cards/sc_st_hayes_01.svg",
    "realisticArt": "assets/cards/sc_st_hayes_01.svg"
  },
  {
    "id": "sc_cm_hunt_02",
    "sport": "Soccer",
    "name": "Ty Hunt",
    "team": "Portland City",
    "pos": "CM",
    "emoji": "\u26bd",
    "rarity": "Common",
    "off": 68,
    "def": 64,
    "ath": 68,
    "iq": 76,
    "desc": "Depth CM who helps complete the binder.",
    "art": "assets/players/sc_cm_hunt_02.svg",
    "cardArt": "assets/cards/sc_cm_hunt_02.svg",
    "realisticArt": "assets/cards/sc_cm_hunt_02.svg"
  },
  {
    "id": "sc_w_cross_03",
    "sport": "Soccer",
    "name": "Kobe Cross",
    "team": "Miami Azul",
    "pos": "W",
    "emoji": "\u26bd",
    "rarity": "Common",
    "off": 62,
    "def": 48,
    "ath": 68,
    "iq": 51,
    "desc": "Depth W who helps complete the binder.",
    "art": "assets/players/sc_w_cross_03.svg",
    "cardArt": "assets/cards/sc_w_cross_03.svg",
    "realisticArt": "assets/cards/sc_w_cross_03.svg"
  },
  {
    "id": "sc_cb_sutton_04",
    "sport": "Soccer",
    "name": "Andre Sutton",
    "team": "Seattle Sound",
    "pos": "CB",
    "emoji": "\u26bd",
    "rarity": "Common",
    "off": 62,
    "def": 84,
    "ath": 60,
    "iq": 69,
    "desc": "Depth CB who helps complete the binder.",
    "art": "assets/players/sc_cb_sutton_04.svg",
    "cardArt": "assets/cards/sc_cb_sutton_04.svg",
    "realisticArt": "assets/cards/sc_cb_sutton_04.svg"
  },
  {
    "id": "sc_gk_barrett_05",
    "sport": "Soccer",
    "name": "Micah Barrett",
    "team": "Vegas United",
    "pos": "GK",
    "emoji": "\u26bd",
    "rarity": "Common",
    "off": 59,
    "def": 64,
    "ath": 53,
    "iq": 59,
    "desc": "Depth GK who helps complete the binder.",
    "art": "assets/players/sc_gk_barrett_05.svg",
    "cardArt": "assets/cards/sc_gk_barrett_05.svg",
    "realisticArt": "assets/cards/sc_gk_barrett_05.svg"
  },
  {
    "id": "sc_am_page_06",
    "sport": "Soccer",
    "name": "Orion Page",
    "team": "Boston Rovers",
    "pos": "AM",
    "emoji": "\u26bd",
    "rarity": "Common",
    "off": 76,
    "def": 53,
    "ath": 63,
    "iq": 75,
    "desc": "Depth AM who helps complete the binder.",
    "art": "assets/players/sc_am_page_06.svg",
    "cardArt": "assets/cards/sc_am_page_06.svg",
    "realisticArt": "assets/cards/sc_am_page_06.svg"
  },
  {
    "id": "sc_cdm_bishop_07",
    "sport": "Soccer",
    "name": "Nico Bishop",
    "team": "Philly Union",
    "pos": "CDM",
    "emoji": "\u26bd",
    "rarity": "Common",
    "off": 58,
    "def": 62,
    "ath": 46,
    "iq": 52,
    "desc": "Depth CDM who helps complete the binder.",
    "art": "assets/players/sc_cdm_bishop_07.svg",
    "cardArt": "assets/cards/sc_cdm_bishop_07.svg",
    "realisticArt": "assets/cards/sc_cdm_bishop_07.svg"
  },
  {
    "id": "sc_fb_valdez_08",
    "sport": "Soccer",
    "name": "Andre Valdez",
    "team": "San Diego Sol",
    "pos": "FB",
    "emoji": "\u26bd",
    "rarity": "Common",
    "off": 69,
    "def": 82,
    "ath": 77,
    "iq": 75,
    "desc": "Depth FB who helps complete the binder.",
    "art": "assets/players/sc_fb_valdez_08.svg",
    "cardArt": "assets/cards/sc_fb_valdez_08.svg",
    "realisticArt": "assets/cards/sc_fb_valdez_08.svg"
  },
  {
    "id": "sc_st_mills_09",
    "sport": "Soccer",
    "name": "Kai Mills",
    "team": "Austin Verde",
    "pos": "ST",
    "emoji": "\u26bd",
    "rarity": "Common",
    "off": 62,
    "def": 53,
    "ath": 63,
    "iq": 53,
    "desc": "Depth ST who helps complete the binder.",
    "art": "assets/players/sc_st_mills_09.svg",
    "cardArt": "assets/cards/sc_st_mills_09.svg",
    "realisticArt": "assets/cards/sc_st_mills_09.svg"
  },
  {
    "id": "sc_cm_maddox_10",
    "sport": "Soccer",
    "name": "Talon Maddox",
    "team": "Portland City",
    "pos": "CM",
    "emoji": "\u26bd",
    "rarity": "Common",
    "off": 54,
    "def": 59,
    "ath": 65,
    "iq": 67,
    "desc": "Depth CM who helps complete the binder.",
    "art": "assets/players/sc_cm_maddox_10.svg",
    "cardArt": "assets/cards/sc_cm_maddox_10.svg",
    "realisticArt": "assets/cards/sc_cm_maddox_10.svg"
  },
  {
    "id": "sc_w_hayes_11",
    "sport": "Soccer",
    "name": "Asher Hayes",
    "team": "Miami Azul",
    "pos": "W",
    "emoji": "\u26bd",
    "rarity": "Uncommon",
    "off": 66,
    "def": 58,
    "ath": 68,
    "iq": 57,
    "desc": "Useful rotation W with upgrade potential.",
    "art": "assets/players/sc_w_hayes_11.svg",
    "cardArt": "assets/cards/sc_w_hayes_11.svg",
    "realisticArt": "assets/cards/sc_w_hayes_11.svg"
  },
  {
    "id": "sc_cb_holloway_12",
    "sport": "Soccer",
    "name": "Julius Holloway",
    "team": "Seattle Sound",
    "pos": "CB",
    "emoji": "\u26bd",
    "rarity": "Uncommon",
    "off": 69,
    "def": 74,
    "ath": 76,
    "iq": 73,
    "desc": "Useful rotation CB with upgrade potential.",
    "art": "assets/players/sc_cb_holloway_12.svg",
    "cardArt": "assets/cards/sc_cb_holloway_12.svg",
    "realisticArt": "assets/cards/sc_cb_holloway_12.svg"
  },
  {
    "id": "sc_gk_holloway_13",
    "sport": "Soccer",
    "name": "Ronan Holloway",
    "team": "Vegas United",
    "pos": "GK",
    "emoji": "\u26bd",
    "rarity": "Uncommon",
    "off": 53,
    "def": 67,
    "ath": 68,
    "iq": 64,
    "desc": "Useful rotation GK with upgrade potential.",
    "art": "assets/players/sc_gk_holloway_13.svg",
    "cardArt": "assets/cards/sc_gk_holloway_13.svg",
    "realisticArt": "assets/cards/sc_gk_holloway_13.svg"
  },
  {
    "id": "sc_am_hayes_14",
    "sport": "Soccer",
    "name": "Orion Hayes",
    "team": "Boston Rovers",
    "pos": "AM",
    "emoji": "\u26bd",
    "rarity": "Uncommon",
    "off": 83,
    "def": 77,
    "ath": 73,
    "iq": 77,
    "desc": "Useful rotation AM with upgrade potential.",
    "art": "assets/players/sc_am_hayes_14.svg",
    "cardArt": "assets/cards/sc_am_hayes_14.svg",
    "realisticArt": "assets/cards/sc_am_hayes_14.svg"
  },
  {
    "id": "sc_cdm_west_15",
    "sport": "Soccer",
    "name": "Marco West",
    "team": "Philly Union",
    "pos": "CDM",
    "emoji": "\u26bd",
    "rarity": "Uncommon",
    "off": 77,
    "def": 75,
    "ath": 76,
    "iq": 79,
    "desc": "Useful rotation CDM with upgrade potential.",
    "art": "assets/players/sc_cdm_west_15.svg",
    "cardArt": "assets/cards/sc_cdm_west_15.svg",
    "realisticArt": "assets/cards/sc_cdm_west_15.svg"
  },
  {
    "id": "sc_fb_sterling_16",
    "sport": "Soccer",
    "name": "Talon Sterling",
    "team": "San Diego Sol",
    "pos": "FB",
    "emoji": "\u26bd",
    "rarity": "Uncommon",
    "off": 60,
    "def": 80,
    "ath": 74,
    "iq": 61,
    "desc": "Useful rotation FB with upgrade potential.",
    "art": "assets/players/sc_fb_sterling_16.svg",
    "cardArt": "assets/cards/sc_fb_sterling_16.svg",
    "realisticArt": "assets/cards/sc_fb_sterling_16.svg"
  },
  {
    "id": "sc_st_mason_17",
    "sport": "Soccer",
    "name": "Nico Mason",
    "team": "Austin Verde",
    "pos": "ST",
    "emoji": "\u26bd",
    "rarity": "Rare",
    "off": 84,
    "def": 69,
    "ath": 78,
    "iq": 70,
    "desc": "Reliable high-ceiling ST for competitive lineups.",
    "art": "assets/players/sc_st_mason_17.svg",
    "cardArt": "assets/cards/sc_st_mason_17.svg",
    "realisticArt": "assets/cards/sc_st_mason_17.svg"
  },
  {
    "id": "sc_cm_price_18",
    "sport": "Soccer",
    "name": "Marco Price",
    "team": "Portland City",
    "pos": "CM",
    "emoji": "\u26bd",
    "rarity": "Rare",
    "off": 77,
    "def": 82,
    "ath": 83,
    "iq": 89,
    "desc": "Reliable high-ceiling CM for competitive lineups.",
    "art": "assets/players/sc_cm_price_18.svg",
    "cardArt": "assets/cards/sc_cm_price_18.svg",
    "realisticArt": "assets/cards/sc_cm_price_18.svg"
  },
  {
    "id": "sc_w_barrett_19",
    "sport": "Soccer",
    "name": "Kellan Barrett",
    "team": "Miami Azul",
    "pos": "W",
    "emoji": "\u26bd",
    "rarity": "Rare",
    "off": 87,
    "def": 86,
    "ath": 81,
    "iq": 75,
    "desc": "Reliable high-ceiling W for competitive lineups.",
    "art": "assets/players/sc_w_barrett_19.svg",
    "cardArt": "assets/cards/sc_w_barrett_19.svg",
    "realisticArt": "assets/cards/sc_w_barrett_19.svg"
  },
  {
    "id": "sc_cb_winters_20",
    "sport": "Soccer",
    "name": "Elias Winters",
    "team": "Seattle Sound",
    "pos": "CB",
    "emoji": "\u26bd",
    "rarity": "Rare",
    "off": 73,
    "def": 95,
    "ath": 84,
    "iq": 78,
    "desc": "Reliable high-ceiling CB for competitive lineups.",
    "art": "assets/players/sc_cb_winters_20.svg",
    "cardArt": "assets/cards/sc_cb_winters_20.svg",
    "realisticArt": "assets/cards/sc_cb_winters_20.svg"
  },
  {
    "id": "sc_gk_hawkins_21",
    "sport": "Soccer",
    "name": "Orion Hawkins",
    "team": "Vegas United",
    "pos": "GK",
    "emoji": "\u26bd",
    "rarity": "Epic",
    "off": 78,
    "def": 95,
    "ath": 83,
    "iq": 83,
    "desc": "Premium GK with elite impact traits.",
    "art": "assets/players/sc_gk_hawkins_21.svg",
    "cardArt": "assets/cards/sc_gk_hawkins_21.svg",
    "realisticArt": "assets/cards/sc_gk_hawkins_21.svg"
  },
  {
    "id": "sc_am_rivera_22",
    "sport": "Soccer",
    "name": "Nico Rivera",
    "team": "Boston Rovers",
    "pos": "AM",
    "emoji": "\u26bd",
    "rarity": "Legendary",
    "off": 93,
    "def": 87,
    "ath": 96,
    "iq": 99,
    "desc": "Franchise-defining AM with chase-card upside.",
    "art": "assets/players/sc_am_rivera_22.svg",
    "cardArt": "assets/cards/sc_am_rivera_22.svg",
    "realisticArt": "assets/cards/sc_am_rivera_22.svg"
  },
  {
    "id": "bs_sp_bishop_01",
    "sport": "Baseball",
    "name": "Reid Bishop",
    "team": "Seattle Cedars",
    "pos": "SP",
    "emoji": "\u26be",
    "rarity": "Common",
    "off": 64,
    "def": 77,
    "ath": 65,
    "iq": 62,
    "desc": "Depth SP who helps complete the binder.",
    "art": "assets/players/bs_sp_bishop_01.svg",
    "cardArt": "assets/cards/bs_sp_bishop_01.svg",
    "realisticArt": "assets/cards/bs_sp_bishop_01.svg"
  },
  {
    "id": "bs_cp_page_02",
    "sport": "Baseball",
    "name": "Cam Page",
    "team": "Phoenix Cactus",
    "pos": "CP",
    "emoji": "\u26be",
    "rarity": "Common",
    "off": 61,
    "def": 76,
    "ath": 50,
    "iq": 60,
    "desc": "Depth CP who helps complete the binder.",
    "art": "assets/players/bs_cp_page_02.svg",
    "cardArt": "assets/cards/bs_cp_page_02.svg",
    "realisticArt": "assets/cards/bs_cp_page_02.svg"
  },
  {
    "id": "bs_c_archer_03",
    "sport": "Baseball",
    "name": "Asher Archer",
    "team": "Austin Bats",
    "pos": "C",
    "emoji": "\u26be",
    "rarity": "Common",
    "off": 71,
    "def": 76,
    "ath": 65,
    "iq": 60,
    "desc": "Depth C who helps complete the binder.",
    "art": "assets/players/bs_c_archer_03.svg",
    "cardArt": "assets/cards/bs_c_archer_03.svg",
    "realisticArt": "assets/cards/bs_c_archer_03.svg"
  },
  {
    "id": "bs_1b_rhodes_04",
    "sport": "Baseball",
    "name": "Amari Rhodes",
    "team": "Portland Pines",
    "pos": "1B",
    "emoji": "\u26be",
    "rarity": "Common",
    "off": 58,
    "def": 56,
    "ath": 51,
    "iq": 45,
    "desc": "Depth 1B who helps complete the binder.",
    "art": "assets/players/bs_1b_rhodes_04.svg",
    "cardArt": "assets/cards/bs_1b_rhodes_04.svg",
    "realisticArt": "assets/cards/bs_1b_rhodes_04.svg"
  },
  {
    "id": "bs_2b_mills_05",
    "sport": "Baseball",
    "name": "Cam Mills",
    "team": "Miami Tides",
    "pos": "2B",
    "emoji": "\u26be",
    "rarity": "Common",
    "off": 70,
    "def": 73,
    "ath": 69,
    "iq": 65,
    "desc": "Depth 2B who helps complete the binder.",
    "art": "assets/players/bs_2b_mills_05.svg",
    "cardArt": "assets/cards/bs_2b_mills_05.svg",
    "realisticArt": "assets/cards/bs_2b_mills_05.svg"
  },
  {
    "id": "bs_3b_bishop_06",
    "sport": "Baseball",
    "name": "Emilio Bishop",
    "team": "Vegas Diamonds",
    "pos": "3B",
    "emoji": "\u26be",
    "rarity": "Common",
    "off": 77,
    "def": 62,
    "ath": 72,
    "iq": 62,
    "desc": "Depth 3B who helps complete the binder.",
    "art": "assets/players/bs_3b_bishop_06.svg",
    "cardArt": "assets/cards/bs_3b_bishop_06.svg",
    "realisticArt": "assets/cards/bs_3b_bishop_06.svg"
  },
  {
    "id": "bs_ss_holloway_07",
    "sport": "Baseball",
    "name": "Cruz Holloway",
    "team": "Boston Lanterns",
    "pos": "SS",
    "emoji": "\u26be",
    "rarity": "Common",
    "off": 50,
    "def": 55,
    "ath": 66,
    "iq": 48,
    "desc": "Depth SS who helps complete the binder.",
    "art": "assets/players/bs_ss_holloway_07.svg",
    "cardArt": "assets/cards/bs_ss_holloway_07.svg",
    "realisticArt": "assets/cards/bs_ss_holloway_07.svg"
  },
  {
    "id": "bs_cf_reed_08",
    "sport": "Baseball",
    "name": "Cam Reed",
    "team": "Carolina Pines",
    "pos": "CF",
    "emoji": "\u26be",
    "rarity": "Common",
    "off": 74,
    "def": 65,
    "ath": 66,
    "iq": 64,
    "desc": "Depth CF who helps complete the binder.",
    "art": "assets/players/bs_cf_reed_08.svg",
    "cardArt": "assets/cards/bs_cf_reed_08.svg",
    "realisticArt": "assets/cards/bs_cf_reed_08.svg"
  },
  {
    "id": "bs_of_hayes_09",
    "sport": "Baseball",
    "name": "Tariq Hayes",
    "team": "Seattle Cedars",
    "pos": "OF",
    "emoji": "\u26be",
    "rarity": "Common",
    "off": 74,
    "def": 57,
    "ath": 65,
    "iq": 64,
    "desc": "Depth OF who helps complete the binder.",
    "art": "assets/players/bs_of_hayes_09.svg",
    "cardArt": "assets/cards/bs_of_hayes_09.svg",
    "realisticArt": "assets/cards/bs_of_hayes_09.svg"
  },
  {
    "id": "bs_dh_bridges_10",
    "sport": "Baseball",
    "name": "Dorian Bridges",
    "team": "Phoenix Cactus",
    "pos": "DH",
    "emoji": "\u26be",
    "rarity": "Common",
    "off": 69,
    "def": 57,
    "ath": 45,
    "iq": 58,
    "desc": "Depth DH who helps complete the binder.",
    "art": "assets/players/bs_dh_bridges_10.svg",
    "cardArt": "assets/cards/bs_dh_bridges_10.svg",
    "realisticArt": "assets/cards/bs_dh_bridges_10.svg"
  },
  {
    "id": "bs_sp_fox_11",
    "sport": "Baseball",
    "name": "Kade Fox",
    "team": "Austin Bats",
    "pos": "SP",
    "emoji": "\u26be",
    "rarity": "Uncommon",
    "off": 69,
    "def": 81,
    "ath": 79,
    "iq": 76,
    "desc": "Useful rotation SP with upgrade potential.",
    "art": "assets/players/bs_sp_fox_11.svg",
    "cardArt": "assets/cards/bs_sp_fox_11.svg",
    "realisticArt": "assets/cards/bs_sp_fox_11.svg"
  },
  {
    "id": "bs_cp_frost_12",
    "sport": "Baseball",
    "name": "Rafael Frost",
    "team": "Portland Pines",
    "pos": "CP",
    "emoji": "\u26be",
    "rarity": "Uncommon",
    "off": 61,
    "def": 72,
    "ath": 68,
    "iq": 72,
    "desc": "Useful rotation CP with upgrade potential.",
    "art": "assets/players/bs_cp_frost_12.svg",
    "cardArt": "assets/cards/bs_cp_frost_12.svg",
    "realisticArt": "assets/cards/bs_cp_frost_12.svg"
  },
  {
    "id": "bs_c_santiago_13",
    "sport": "Baseball",
    "name": "Nico Santiago",
    "team": "Miami Tides",
    "pos": "C",
    "emoji": "\u26be",
    "rarity": "Uncommon",
    "off": 66,
    "def": 68,
    "ath": 56,
    "iq": 69,
    "desc": "Useful rotation C with upgrade potential.",
    "art": "assets/players/bs_c_santiago_13.svg",
    "cardArt": "assets/cards/bs_c_santiago_13.svg",
    "realisticArt": "assets/cards/bs_c_santiago_13.svg"
  },
  {
    "id": "bs_1b_valdez_14",
    "sport": "Baseball",
    "name": "Bruno Valdez",
    "team": "Vegas Diamonds",
    "pos": "1B",
    "emoji": "\u26be",
    "rarity": "Uncommon",
    "off": 74,
    "def": 57,
    "ath": 66,
    "iq": 63,
    "desc": "Useful rotation 1B with upgrade potential.",
    "art": "assets/players/bs_1b_valdez_14.svg",
    "cardArt": "assets/cards/bs_1b_valdez_14.svg",
    "realisticArt": "assets/cards/bs_1b_valdez_14.svg"
  },
  {
    "id": "bs_2b_winters_15",
    "sport": "Baseball",
    "name": "Roman Winters",
    "team": "Boston Lanterns",
    "pos": "2B",
    "emoji": "\u26be",
    "rarity": "Uncommon",
    "off": 65,
    "def": 61,
    "ath": 68,
    "iq": 63,
    "desc": "Useful rotation 2B with upgrade potential.",
    "art": "assets/players/bs_2b_winters_15.svg",
    "cardArt": "assets/cards/bs_2b_winters_15.svg",
    "realisticArt": "assets/cards/bs_2b_winters_15.svg"
  },
  {
    "id": "bs_3b_cannon_16",
    "sport": "Baseball",
    "name": "Jace Cannon",
    "team": "Carolina Pines",
    "pos": "3B",
    "emoji": "\u26be",
    "rarity": "Uncommon",
    "off": 75,
    "def": 70,
    "ath": 76,
    "iq": 68,
    "desc": "Useful rotation 3B with upgrade potential.",
    "art": "assets/players/bs_3b_cannon_16.svg",
    "cardArt": "assets/cards/bs_3b_cannon_16.svg",
    "realisticArt": "assets/cards/bs_3b_cannon_16.svg"
  },
  {
    "id": "bs_ss_hawkins_17",
    "sport": "Baseball",
    "name": "Isaiah Hawkins",
    "team": "Seattle Cedars",
    "pos": "SS",
    "emoji": "\u26be",
    "rarity": "Rare",
    "off": 86,
    "def": 80,
    "ath": 84,
    "iq": 81,
    "desc": "Reliable high-ceiling SS for competitive lineups.",
    "art": "assets/players/bs_ss_hawkins_17.svg",
    "cardArt": "assets/cards/bs_ss_hawkins_17.svg",
    "realisticArt": "assets/cards/bs_ss_hawkins_17.svg"
  },
  {
    "id": "bs_cf_sterling_18",
    "sport": "Baseball",
    "name": "Dante Sterling",
    "team": "Phoenix Cactus",
    "pos": "CF",
    "emoji": "\u26be",
    "rarity": "Rare",
    "off": 81,
    "def": 87,
    "ath": 81,
    "iq": 79,
    "desc": "Reliable high-ceiling CF for competitive lineups.",
    "art": "assets/players/bs_cf_sterling_18.svg",
    "cardArt": "assets/cards/bs_cf_sterling_18.svg",
    "realisticArt": "assets/cards/bs_cf_sterling_18.svg"
  },
  {
    "id": "bs_of_hayes_19",
    "sport": "Baseball",
    "name": "Bruno Hayes",
    "team": "Austin Bats",
    "pos": "OF",
    "emoji": "\u26be",
    "rarity": "Rare",
    "off": 78,
    "def": 73,
    "ath": 75,
    "iq": 69,
    "desc": "Reliable high-ceiling OF for competitive lineups.",
    "art": "assets/players/bs_of_hayes_19.svg",
    "cardArt": "assets/cards/bs_of_hayes_19.svg",
    "realisticArt": "assets/cards/bs_of_hayes_19.svg"
  },
  {
    "id": "bs_dh_price_20",
    "sport": "Baseball",
    "name": "Kobe Price",
    "team": "Portland Pines",
    "pos": "DH",
    "emoji": "\u26be",
    "rarity": "Rare",
    "off": 80,
    "def": 81,
    "ath": 75,
    "iq": 83,
    "desc": "Reliable high-ceiling DH for competitive lineups.",
    "art": "assets/players/bs_dh_price_20.svg",
    "cardArt": "assets/cards/bs_dh_price_20.svg",
    "realisticArt": "assets/cards/bs_dh_price_20.svg"
  },
  {
    "id": "bs_sp_frost_21",
    "sport": "Baseball",
    "name": "Mateo Frost",
    "team": "Miami Tides",
    "pos": "SP",
    "emoji": "\u26be",
    "rarity": "Epic",
    "off": 89,
    "def": 99,
    "ath": 89,
    "iq": 93,
    "desc": "Premium SP with elite impact traits.",
    "art": "assets/players/bs_sp_frost_21.svg",
    "cardArt": "assets/cards/bs_sp_frost_21.svg",
    "realisticArt": "assets/cards/bs_sp_frost_21.svg"
  },
  {
    "id": "bs_cp_pierce_22",
    "sport": "Baseball",
    "name": "Elias Pierce",
    "team": "Vegas Diamonds",
    "pos": "CP",
    "emoji": "\u26be",
    "rarity": "Legendary",
    "off": 89,
    "def": 99,
    "ath": 84,
    "iq": 95,
    "desc": "Franchise-defining CP with chase-card upside.",
    "art": "assets/players/bs_cp_pierce_22.svg",
    "cardArt": "assets/cards/bs_cp_pierce_22.svg",
    "realisticArt": "assets/cards/bs_cp_pierce_22.svg"
  }
];

const PACKS = {
  "rookie": {
    "name": "Rookie Pack",
    "cost": 45,
    "count": 3,
    "desc": "Cheap entry pack. Mostly Common and Uncommon, with a tiny dream-pull chance.",
    "sport": null,
    "weights": "rookie"
  },
  "pro": {
    "name": "Pro Pack",
    "cost": 90,
    "count": 4,
    "desc": "First unlocked upgrade pack. Better Rare odds than Rookie without targeting one sport.",
    "sport": null,
    "weights": "pro"
  },
  "star": {
    "name": "All-Star Pack",
    "cost": 190,
    "count": 4,
    "desc": "Mid-game chase pack with strong Rare odds and meaningful Epic access.",
    "sport": null,
    "weights": "star"
  },
  "hof": {
    "name": "Hall of Fame Pack",
    "cost": 475,
    "count": 5,
    "desc": "Late-game premium pack. Best shot at Epic and Legendary cards.",
    "sport": null,
    "weights": "hof"
  }
};

const RARITY_WEIGHTS = {
  "rookie": {
    "Common": 72,
    "Uncommon": 24,
    "Rare": 3.75,
    "Epic": 0.24,
    "Legendary": 0.01
  },
  "pro": {
    "Common": 58,
    "Uncommon": 31,
    "Rare": 9.5,
    "Epic": 1.4,
    "Legendary": 0.1
  },
  "star": {
    "Common": 38,
    "Uncommon": 37,
    "Rare": 20,
    "Epic": 4.5,
    "Legendary": 0.5
  },
  "hof": {
    "Common": 20,
    "Uncommon": 30,
    "Rare": 32,
    "Epic": 15,
    "Legendary": 3
  }
};

const OPPONENTS = [
  {
    "name": "Local Card Kid",
    "emoji": "🧢",
    "level": 1,
    "bonus": 0
  },
  {
    "name": "Saturday Shop Regular",
    "emoji": "🛒",
    "level": 2,
    "bonus": 3
  },
  {
    "name": "Binder Boss",
    "emoji": "📚",
    "level": 3,
    "bonus": 6
  },
  {
    "name": "Trade Night Champ",
    "emoji": "🏅",
    "level": 4,
    "bonus": 9
  },
  {
    "name": "National Collector",
    "emoji": "🏆",
    "level": 5,
    "bonus": 12
  }
];

const QUESTS = [
  {
    "id": "first_pack",
    "title": "Open your first pack",
    "text": "Open any sports card pack.",
    "reward": 35
  },
  {
    "id": "one_each",
    "title": "Collect all four sports",
    "text": "Own at least one football, basketball, soccer, and baseball card.",
    "reward": 80
  },
  {
    "id": "five_lineup",
    "title": "Build a full lineup",
    "text": "Put 5 cards in your active lineup.",
    "reward": 65
  },
  {
    "id": "first_win",
    "title": "Win a quick match",
    "text": "Win one best-of-five collector match.",
    "reward": 75
  },
  {
    "id": "rare_pull",
    "title": "Pull a Rare or better",
    "text": "Own at least one Rare, Epic, or Legendary card.",
    "reward": 90
  },
  {
    "id": "ten_unique",
    "title": "Collect 10 unique cards",
    "text": "Own 10 different cards.",
    "reward": 110
  },
  {
    "id": "cup_game",
    "title": "Submit a Collector Cup lineup",
    "text": "Submit a 5-card lineup snapshot to the Collector Cup.",
    "reward": 60
  },
  {
    "id": "fifty_unique",
    "title": "Collect 50 unique cards",
    "text": "Own 50 different cards.",
    "reward": 225
  },
  {
    "id": "hundred_unique",
    "title": "Collect 100 unique cards",
    "text": "Own 100 different cards.",
    "reward": 500
  }
];
